[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "http://localhost:8000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://ai-price-aggregator-backend.vercel.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://ai-price-aggregator-backend.vercel.app"
