[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://price-comparison-seven.vercel.app"

[[redirects]]
  from = "/api/*"
  to = "https://price-comparison-seven.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://price-comparison-seven.vercel.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://price-comparison-seven.vercel.app"
